/*
 * JobSearch API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.4-release
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Address;
import io.swagger.client.model.Company2;
import io.swagger.client.model.Contacts;
import io.swagger.client.model.Status;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Vacancy2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-20T17:46:18.738Z[GMT]")
public class Vacancy2 {
  @SerializedName("address")
  private Address address = null;

  @SerializedName("specializationName")
  private String specializationName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("companyReference")
  private String companyReference = null;

  @SerializedName("experience")
  private String experience = null;

  @SerializedName("salary")
  private String salary = null;

  @SerializedName("skills")
  private String skills = null;

  @SerializedName("reference")
  private String reference = null;

  @SerializedName("schedule")
  private String schedule = null;

  @SerializedName("company2")
  private Company2 company2 = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("contacts")
  private Contacts contacts = null;

  @SerializedName("vacancyId")
  private Long vacancyId = null;

  @SerializedName("status")
  private Status status = null;

  public Vacancy2 address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public Vacancy2 specializationName(String specializationName) {
    this.specializationName = specializationName;
    return this;
  }

   /**
   * Get specializationName
   * @return specializationName
  **/
  @Schema(description = "")
  public String getSpecializationName() {
    return specializationName;
  }

  public void setSpecializationName(String specializationName) {
    this.specializationName = specializationName;
  }

  public Vacancy2 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Vacancy2 companyReference(String companyReference) {
    this.companyReference = companyReference;
    return this;
  }

   /**
   * Get companyReference
   * @return companyReference
  **/
  @Schema(description = "")
  public String getCompanyReference() {
    return companyReference;
  }

  public void setCompanyReference(String companyReference) {
    this.companyReference = companyReference;
  }

  public Vacancy2 experience(String experience) {
    this.experience = experience;
    return this;
  }

   /**
   * Get experience
   * @return experience
  **/
  @Schema(description = "")
  public String getExperience() {
    return experience;
  }

  public void setExperience(String experience) {
    this.experience = experience;
  }

  public Vacancy2 salary(String salary) {
    this.salary = salary;
    return this;
  }

   /**
   * Get salary
   * @return salary
  **/
  @Schema(description = "")
  public String getSalary() {
    return salary;
  }

  public void setSalary(String salary) {
    this.salary = salary;
  }

  public Vacancy2 skills(String skills) {
    this.skills = skills;
    return this;
  }

   /**
   * Get skills
   * @return skills
  **/
  @Schema(description = "")
  public String getSkills() {
    return skills;
  }

  public void setSkills(String skills) {
    this.skills = skills;
  }

  public Vacancy2 reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @Schema(description = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public Vacancy2 schedule(String schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @Schema(description = "")
  public String getSchedule() {
    return schedule;
  }

  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }

  public Vacancy2 company2(Company2 company2) {
    this.company2 = company2;
    return this;
  }

   /**
   * Get company2
   * @return company2
  **/
  @Schema(description = "")
  public Company2 getCompany2() {
    return company2;
  }

  public void setCompany2(Company2 company2) {
    this.company2 = company2;
  }

  public Vacancy2 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Vacancy2 contacts(Contacts contacts) {
    this.contacts = contacts;
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  @Schema(description = "")
  public Contacts getContacts() {
    return contacts;
  }

  public void setContacts(Contacts contacts) {
    this.contacts = contacts;
  }

  public Vacancy2 vacancyId(Long vacancyId) {
    this.vacancyId = vacancyId;
    return this;
  }

   /**
   * Get vacancyId
   * @return vacancyId
  **/
  @Schema(description = "")
  public Long getVacancyId() {
    return vacancyId;
  }

  public void setVacancyId(Long vacancyId) {
    this.vacancyId = vacancyId;
  }

  public Vacancy2 status(Status status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Status getStatus() {
    return status;
  }

  public void setStatus(Status status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vacancy2 vacancy2 = (Vacancy2) o;
    return Objects.equals(this.address, vacancy2.address) &&
        Objects.equals(this.specializationName, vacancy2.specializationName) &&
        Objects.equals(this.description, vacancy2.description) &&
        Objects.equals(this.companyReference, vacancy2.companyReference) &&
        Objects.equals(this.experience, vacancy2.experience) &&
        Objects.equals(this.salary, vacancy2.salary) &&
        Objects.equals(this.skills, vacancy2.skills) &&
        Objects.equals(this.reference, vacancy2.reference) &&
        Objects.equals(this.schedule, vacancy2.schedule) &&
        Objects.equals(this.company2, vacancy2.company2) &&
        Objects.equals(this.name, vacancy2.name) &&
        Objects.equals(this.contacts, vacancy2.contacts) &&
        Objects.equals(this.vacancyId, vacancy2.vacancyId) &&
        Objects.equals(this.status, vacancy2.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, specializationName, description, companyReference, experience, salary, skills, reference, schedule, company2, name, contacts, vacancyId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vacancy2 {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    specializationName: ").append(toIndentedString(specializationName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    companyReference: ").append(toIndentedString(companyReference)).append("\n");
    sb.append("    experience: ").append(toIndentedString(experience)).append("\n");
    sb.append("    salary: ").append(toIndentedString(salary)).append("\n");
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    company2: ").append(toIndentedString(company2)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    vacancyId: ").append(toIndentedString(vacancyId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
